### ISSUE TITLE
SSL routines - wrong version number, upgrade nodemailer and add options for tls version

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#192]
### Discussed in https://github.com/canarytrace/documentation/discussions/188

<div type='discussions-op-text'>

<sup>Originally posted by **Mato816** April  5, 2023</sup>
Hi,

i have problem with configuration for listener.
In YAML CronJob we set:

- SMTP_SERVER
- SMTP_PORT
- SMTP_USER
- SMTP_PASS

After running CronJob we got following error message:

Error: {"library":"SSL routines","reason":"wrong version number","code":"ESOCKET","command":"CONN"}
at /opt/canary-listener/reporters/email.js:116:13
at /opt/canary-listener/node_modules/nodemailer/lib/mailer/index.js:226:21
at SMTPConnection.<anonymous> (/opt/canary-listener/node_modules/nodemailer/lib/smtp-transport/index.js:175:24)
at Object.onceWrapper (node:events:628:26)
at SMTPConnection.emit (node:events:513:28)
at SMTPConnection._onError (/opt/canary-listener/node_modules/nodemailer/lib/smtp-connection/index.js:764:14)
at SMTPConnection._onSocketError (/opt/canary-listener/node_modules/nodemailer/lib/smtp-connection/index.js:190:45)
at TLSSocket.emit (node:events:513:28)
at emitErrorNT (node:internal/streams/destroy:151:8)
at emitErrorCloseNT (node:internal/streams/destroy:116:3)
Node.js v18.7.0
Listener agent: end of analysis

Can you help me please with this issue?
Thank you.</div>

**Comment by rdpanek** [comment]
- [x] upgraded nodejs (node:18.7.0-alpine3.15)
- [x] upgrade nodemailer ("nodemailer": "6.9.4",)

- [x] add env for choose version of the tls min and max
```
const tlsMinVersion = process.env.TLS_MIN_VERSION ? process.env.TLS_MIN_VERSION : `TLSv1.2` // default TLSv1.2
const tlsMaxVersion = process.env.TLS_MAX_VERSION ? process.env.TLS_MAX_VERSION : `TLSv1.3` // default TLSv1.3
const tlsRejectUnauthorized = process.env.TLS_REJECT_UNAUTHORIZED ? true : false // default false
const printConfiguration = process.env.PRINT_MAIL_CONFIGURATION ? process.env.PRINT_MAIL_CONFIGURATION : false // default false
```
Documentation: https://www.npmjs.com/package/nodemailer
